# Generated by Django 4.1.3 on 2022-11-26 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videos', '0003_alter_movie_options_movie_link_movie_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='user',
            field=models.ForeignKey(default='paul', on_delete=django.db.models.deletion.CASCADE, related_name='Movie', to=settings.AUTH_USER_MODEL),
        ),
    ]
