# Generated by Django 4.1.3 on 2022-11-28 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
