# Generated by Django 4.1.3 on 2022-11-28 04:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_alter_movie_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='you_tube_insert',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
