# Generated by Django 4.1.3 on 2022-12-03 12:45

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_movie_you_tube_insert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='you_tube_insert',
            field=embed_video.fields.EmbedVideoField(),
        ),
    ]
