# Generated by Django 4.1.3 on 2022-12-03 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_alter_movie_you_tube_insert'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='link1',
            field=models.CharField(default='no_hay_nada', max_length=30),
        ),
    ]
